### ISSUE TITLE
fixed dimensions reference pattern

### ISSUE THREAD

**Issue by benmarwick** [BeebBenjamin/table-py#1]
I came here from your wonderful JASR paper, what a great study! Do you happen to have a PDF of the fixed dimensions reference pattern available? In Fig 1 there is one kind, but in supp fig 1 it looks like you've just stuck a map on the turntable... Do you have the Fig 1 file available? Thanks!

**Comment by BeebBenjamin** [comment]
Hi.  Apologies.  I wasn't expecting anyone to post requests via github.  We do not use that reference pattern any more and I personally do not have it.  If you want it maybe email the corresponding author Allown Evin.  Depending on what reconstruction software you are using you can print off coded targets to aid in scaling and photo alignment.  I personally use photoscan, and you can even print off the coded targets in demo mode without paying for a licence!
